### ISSUE TITLE
Add another doctrine type to reorder UUID v1 to improve MySQL performance

### ISSUE THREAD

**Issue by kamazee** [ramsey/uuid-doctrine#14]
There's [an interesting article](https://www.percona.com/blog/2014/12/19/store-uuid-optimized-way/) in Percona blog that claims that due to InnoDB's internals it prefers sequential primary keys rather than completely random ones so one can simply leverage features of time-based UUID v1 to improve InnoDB performance.

Do you think it would be useful to have another doctrine type that reorders UUID in the way described in the article? There's a downside, of course: this hacky way of representing a UUID is somewhat more complicated to deal with (migrating to another column type looks more painful, for example) but still, graphs the author drew look promising and the amount of code to implement it seems to be quite small. What's your opinion on adding it?

**Comment by ramsey** [comment]
Take a look at [PR #118](https://github.com/ramsey/uuid/pull/118) on ramsey/uuid. It does exactly this. After I do some benchmarking on it (trying to show the same results as the Percona blog), I’ll merge it in, and then it’d be awesome to see a PR on this repo that creates a separate Doctrine type for it.

Thanks!

**Comment by JCMais** [comment]
@ramsey The PR referenced was merged, any plans to add that type here?

**Comment by ramsey** [comment]
@JCMais I'd love to add a separate type here for the InnoDB-optimized UUID. It's on my radar, which is why I'm keeping this issue open. I haven't begun any work on it, yet, so if you're asking it about because you're interested in submitting a PR, feel free to do so. :-)

**Comment by JCMais** [comment]
I'm already using it, since I just needed to create a single class on my application and not use the ``UuidGenerator`` provider.

Isn't just a matter of using ``uuid1`` instead of ``uuid4``?

Configuration should be left to the user.

**Comment by ramsey** [comment]
To use the optimized UUID for InnoDB, you'll need to store the value in MySQL as binary data, so you will need to take the concepts provided in uuid-doctrine's `uuid_binary` type and also make changes when converting to a database value and back to a PHP value.

Here's an example of how to use it (not with Doctrine):

``` php
$factory = new \Ramsey\Uuid\UuidFactory();
$codec = new OrderedTimeCodec($factory->getUuidBuilder());
$factory->setCodec($codec);
Uuid::setFactory($factory);

$uuid1 = Uuid::uuid1();
echo $uuid1->toString() . "\n"; // i.e. 58e0a7d7-eebc-11d8-9669-0800200c9a66
$optimized = $uuid1->getBytes();
// Store $optimized to the database in a 16-char field
echo Uuid::fromBytes($optimized)->toString() . "\n"; // i.e. 58e0a7d7-eebc-11d8-9669-0800200c9a66
```

Making it ready for ramsey/uuid-doctrine is a matter of creating a new DBAL type (i.e. `uuid_binary_ordered_time`?) and providing the appropriate `convertToPHPValue()` and `convertToDatabaseValue()` methods. In theory, one could just extend `UuidBinaryType` and override the `NAME` constant and the `convertToDatabaseValue()` method. I think. :-)

**Comment by JCMais** [comment]
@ramsey I was checking some info on the COMB generator and I saw the following PR: https://github.com/ramsey/uuid/pull/102

Using ``TimestampFirstCombCodec`` basically accomplishes that, doesn't it?

**Comment by ramsey** [comment]
`TimestampFirstCombCodec` is different from the `OrderedTimeCodec`, though their names aren't very clear. I need to write up some documentation to help explain the differences.

`TimestampFirstCombCodec` is intended to be used together with `CombGenerator`.

The `CombGenerator` generates random bytes and then adds a timestamp as the last 6 bytes of the returned binary data. This allows v4 UUIDs to contain the timestamp on which they were generated. "COMB" means "combined GUID and timestamp," referencing the fact that GUIDs are random, so this is a combination of a random (v4) UUID with a timestamp on the end.

`TimestampFirstCombCodec` may be used with the `CombGenerator` to move the timestamp to the beginning of the UUID (the first 6 bytes, instead of the last 6 bytes). This allows for COMB UUIDs to be ordered in the sequence in which they were created.

`TimestampLastCombCodec` is a dummy codec that effectively does exactly what `CombGenerator` does on its own, but it's there for completeness.

On the other hand, `OrderedTimeCodec` is intended to be used with a time-based (v1) UUID. The standard layout of a UUID is:

```
time_low - time_mid - time_hi_and_version - clock_seq_hi_and_reserved - clock_seq_low - node
```

The `OrderedTimeCoded` rearranges a v1 UUID so that the layout becomes:

```
time_hi_and_version - time_mid - time_low - clock_seq_hi_and_reserved - clock_seq_low - node
```

By rearranging the time parts in this order, they become sequential, allowing the database to store them in a more efficient, optimized way.

If you wish to generate v4 UUIDs and use these as PKs in your database, then your best option is to use `CombGenerator` with `TimestampFirstCombCodec`.

If you wish to generate v1 UUIDs and use these as PKs in your database, then your best option is to use `OrderedTimeCodec`.

There are different reasons for using v1 or v4 UUIDs. v4 UUIDs are truly random. v1 UUIDs include the timestamp they were created, as well as the node on which they were created, and you are able to decompose v1 UUIDs to read this information. v4 UUIDs include no such information.

It's up to you to choose which is most appropriate for your application. However, the ramsey/uuid-doctrine library does not include out-of-the-box support for either type. You have to roll your own, but I am open to PRs to add this support. ;-)

**Comment by ramsey** [comment]
Merged in. Will cut a release soon. Thanks!
