### ISSUE TITLE
Should i pass uuid into a id variable in the entity constructor?

### ISSUE THREAD

**Issue by PaYo90** [ramsey/uuid-doctrine#155]
In regular uuid we do that. with uuid-doctrine, i dont know if should i do that. Documentattion says  nothing about this, but when i try to inicialize entity in  the controller, and give a ID value of that entity in the next entity before flush, the ID isEmpty. What should i write, now?

**Comment by Saeven** [comment]
If you're using the UUID as an ID, you can use the UuidBinaryType with @GeneratedValue - works very well.  If you are otherwise using the popular public-id, with private uuid method, then Doctrine supports only one @GeneratedValue. You'll put that on your id integer, and you can push the UUID into the constructor, or assume it within the constructor. YMMV.
