### ISSUE TITLE
[Question] ConversionException or return as-is

### ISSUE THREAD

**Issue by phoenixgao** [ramsey/uuid-doctrine#21]
I have a field that is uuid, when I search this field with an invalid uuid (a string), it throws a ConversionException, but I was expecting database gives me a not found and return null.

Is there any advantage having this exception?

**Comment by ramsey** [comment]
My guess is that you're hitting that ConversionException either [here](https://github.com/ramsey/uuid-doctrine/blob/e5381b266d19bc9d9dc17447f96df47e5f6e3f1c/src/UuidBinaryType.php#L82-L99) (if using type `uuid_binary`) or [here](https://github.com/ramsey/uuid-doctrine/blob/e5381b266d19bc9d9dc17447f96df47e5f6e3f1c/src/UuidType.php#L77-L88) (if using type `uuid`).

In either case, when preparing the query for the database, the type attempts to convert the value to a UUID for the database, and it fails because the value is invalid.

The ConversionException is from `Doctrine\DBAL\Types`, and it makes sense when attempting to store a value to the database, but it doesn't necessarily make sense when doing queries. Since I'm not a power Doctrine user, I'll ask around to see how others handle similar cases.

Thanks!

**Comment by lcobucci** [comment]
@phoenixgao @ramsey it's exactly that... before even running the query DBAL tries to [convert the data into dabase type](https://github.com/doctrine/dbal/blob/51f6934c19635fa1c69680482522c734a0121463/lib/Doctrine/DBAL/Connection.php#L1488).

You would never have a `null` return in that case.

**Comment by ramsey** [comment]
@lcobucci Is there a better way to handle this for queries? I assume the OP's desire is to actually make the query and get back `0` results.

**Comment by willemwollebrants** [comment]
I think it's worth looking at how the built-in types handle this. Something like the DateTime is a good example, because it also needs to get a value that is either a DateTime or can be converted to one. 

[Looking at the code there](https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Types/DateTimeType.php#L66) I see the same logic: if $value cannot be converted to what we need, throw an exception. 

(I should probably note that DBAL does not throw an exception if you use the built-int Guid field. It doesn't check anything there and treats the field as a regular text field. )

Another reason why I like having this exception is that you know there will never be a row that matches an invalid uuid, so you can avoid bothering the database in this case. 

Lastly, I feel that there is a difference between "there are no rows that match your query" and "your query is invalid", but that depends on the application.

**Comment by lcobucci** [comment]
> Is there a better way to handle this for queries? 

That's a good question... I see that conversion error as a precondition for your query and I'd say that we should filter/sanitize the value before reaching that area. But as @willemwollebrants said "that depends on the application".

**Comment by carnage** [comment]
I think the conversion exception is correct behaviour here. 

Either catch the exception and handle or pre-screen your input for validity.

**Comment by ramsey** [comment]
@phoenixgao, looks like the ConversionException is the correct approach here. Either catch that exception or use `Uuid::isValid()` before making your query to determine whether the UUID is valid.

Thanks, everyone, for your help!

**Comment by phoenixgao** [comment]
Yes at first I was considering the uuid field as just a regular string field, so I expected 0 results from database, but as @willemwollebrants pointed out, even in the database it's a string field, but in php it should be considered as a special uuid field and should let the query hit db only if it is a valid uuid value, since the application should already know that field is a uuid field, then all make sense now.

Thanks everyone!
