### ISSUE TITLE
Using uuid_binary in relations

### ISSUE THREAD

**Issue by exptom** [ramsey/uuid-doctrine#24]
Hi,

Do you have any pointers on how to use uuid_binary in relations?
Specifically I have a many-to-many relation and want the collection to be indexed by the uuid. If I specify the `index-by="id"` property the the collection key is binary:

![xdebug output](https://cdn.pbrd.co/images/sihDH9eTk.png)

Ideally the index should be the string representation of the uuid object as otherwise it is not easy to write methods to interact with the collection (e.g. a `has($entity)` method on the relation)

**Comment by SenseException** [comment]
Do I get you right, that you're using a binary representation of an uuid as the table's id (PK), but for the collection's keys, you want it to be a string?

**Comment by tgalopin** [comment]
IMHO, you should use uuid as secondary keys abs use internal, incremental keys for foreign keys. They are both easier to manipulate (in your case for instance) and more performant, while keeping the usefulness of uuid.

**Comment by exptom** [comment]
@SenseException Yes, as currently I cannot manipulate the collection easily e.g.

    <?php
    public function hasClient(Client $client)
    {
        return array_key_exists($client->getId(),$this->clients);
    }

@tgalopin If i use the auto increment as a secondary key I cannot relate entities easily before persisting them. E.g. I cannot add an `addClient(Client $client)` method to my `User` entity to create the link as I do not know the seconday key until I have persisted.

**Comment by SenseException** [comment]
@exptom If `hasClient()` is the only use case, can you use `Collection::contains()` of the Doctrine Collection to check for an existing Client in there? This way, you don't need the index key.
Otherwise, maybe you can use the `Selectable::matching()` on the collection for finding the Client in your Collection.

**Comment by exptom** [comment]
@SenseException Thanks, that is what I have done. I was hoping for a more performant solution where I could just check for the existence of an array key but that works :smile:

**Comment by nreynis** [comment]
I have a related issue:
When using an uuid_binary relation winth indexBy id, the Doctrine collection will use the binary relation has a key like @exptom explained.
The issue is that if you then try to make a FormType for this entity, you won't be able to do anything. The ArrayCollection being indexed by binary id will throw when `mapDataToForms` will validate the child item name:
https://github.com/symfony/form/blob/master/FormConfigBuilder.php#L775
Not using `indexBy` isn't an option because the form will then try to update the primary key.
