### ISSUE TITLE
Unexpected return value

### ISSUE THREAD

**Issue by Vandersteen** [ramsey/uuid-doctrine#43]
Hello,

I've encountered some unexpected behaviour using UUID's and doctrine relations:

Lets say I have the 2 following classes

**Car**

    class Car
    {
        /**
         * @var Uuid
         *
         * @ORM\Id()
         * @ORM\Column(type="uuid")
         */
        private $id;
    
        /**
         * @var Person
         *
         * @ORM\ManyToOne(targetEntity="Person")
         */
        private $owner;
    
        /**
         * @return Uuid
         */
        public function getId(): Uuid
        {
            return $this->id;
        }
    
        /**
         * @return Person
         */
        public function getOwner(): Person
        {
            return $this->owner;
        }
    }

**Person**

    class Person
    {
        /**
         * @var Uuid
         *
         * @ORM\Id()
         * @ORM\Column(type="uuid")
         */
        private $id;
    
        /**
         * @var string
         *
         * @ORM\Column(type="string")
         */
        private $name;
    
        /**
         * @return Uuid
         */
        public function getId(): Uuid
        {
            return $this->id;
        }
    
        /**
         * @return string
         */
        public function getName(): string
        {
            return $this->name;
        }
    }

Using it as follows errors with: **Expected return type of UUID, string returned**

    $car = $this->carRepo->findOneById($id);
    $car->getOwner()->getId();  /**  returns string */

The following does work

    $car = $this->carRepo->findOneById($id);
    $car->getOwner()->getName();
    $car->getOwner()->getId();  /** returns UUID */

From what I understand, It returns a string because doctrine will create a 'proxy' with the id pre-filled until a property is accessed and the entity 'initialised'.

I could add the following in the getId() method:

     if(is_string($this->id))
     {
            $this->id = UUID::fromString($this->id);
     }

But this kinda beats the purpose of types.

So my questions are:

* Am I missing something in the annotations ?
* Is this a bug I should report at doctrine ?

**Comment by ramsey** [comment]
It’s. It enough to set the column type to “uuid,” since that will use Doctrine’s internal UUID generator, which is string-based. If you’d like to use ramsey/uuid, you need more annotations:

```
    /**
     * @Id
     * @Column(type="uuid", unique=true)
     * @GeneratedValue(strategy="CUSTOM")
     * @CustomIdGenerator(class="Ramsey\Uuid\Doctrine\UuidGenerator")
     */
```

The custom strategy and generator class references are important to get Doctrine to return a Uuid object, instead of string.

**Comment by Vandersteen** [comment]
Oh i forgot to mention i do have the following in **config.yml** :

    uuid:  Ramsey\Uuid\Doctrine\UuidType

And in the constructor I do:

    public function __construct()
    {
        $this->id = Uuid::uuidv4();
    }

Will this be affected by the @CustomIdGenerator(class="Ramsey\Uuid\Doctrine\UuidGenerator") / @GeneratedValue(strategy="CUSTOM").

**Comment by Vandersteen** [comment]
I've just tried it out, changing the annotations does not fix the issue, i still get 

    Return value of Person::getId() must be an instance of Ramsey\Uuid\Uuid, string returned

**Comment by mcneely** [comment]
What happens when you ditch chaining and declare owner as a variable?

**Comment by stof** [comment]
This is a known issue of Doctrine currently. When creating a proxy object (which is the case here for the owner), type conversions are not properly applied. This is why the id is returned as a string before initialization (it works fine after initialization due to the initialization setting all properties from the loaded data with the right type, including the id).
https://github.com/doctrine/doctrine2/pull/6719 fixes it for Doctrine 3 (which is still far from being ready) thanks to the full rewriting of the proxy layer.

**Comment by Vandersteen** [comment]
Ok thanks for confirming @stof.
I guess i need to improve my google skills
