### ISSUE TITLE
Generate Uuid manually in constructor or via UuidGenerator annotation

### ISSUE THREAD

**Issue by flaushi** [ramsey/uuid-doctrine#66]
Hi,
I am really confused about a very elementary question, which I [described on SO](https://stackoverflow.com/questions/53045546/generate-uuid-manually-in-constructor-or-via-uuidgenerator-annotation) clearly.
I'd be very thankful to get a concise answer. I think the documentation should also be complemented in this respect, which I would offer to do.

Thanks in advance,
Olli

**Comment by GraneDirval** [comment]
If you want to get uuid before saving object, you must add it in constructor, otherwise it will be generated while saving object.

**Comment by hkdobrev** [comment]
Does anyone have any input on whether UUID in the constructor is preferred? E.g. not using the database for the primary key and allowing `getId()` method to always return a value.
Would support for both methods be offered in this library and the user can choose if they want to call a method in the constructor?

**Comment by flaushi** [comment]
I think for most people the constructor is preferred, because the id is available right away. I fact for me this was the reason to switch to uuid's.
One thing: If I had known beforehand about https://medium.com/tarkalabs-til/ulids-sortable-uuids-914670129cee, I'd have decided for those...there exist php implementations as well

**Comment by hkdobrev** [comment]
@flaushi Thanks for this! Sortable UUIDs definitely seem interesting for cases where the imposed limits are fine.

@ramsey Do you have any input on this? Would you consider this integration and its documentation to recommend UUIDs in the constructor?

**Comment by ramsey** [comment]
I'm open to improving the documentation in the README to describe the use of UUIDs in the constructor. However, I hesitate to say that it's the *preferred* or *recommended* approach, since everyone's use-cases are different.

As far as sortable UUIDs go, you might want to take a look here: <https://github.com/ramsey/uuid-doctrine#innodb-optimised-binary-uuids>. These are sortable (the binary representation is, not the string representation). I'm also considering supporting ULIDs in version 4.0 of ramsey/uuid, since they are compatible with UUIDs.

**Comment by hkdobrev** [comment]
Thank you for the response! I'll see if I can contribute a bit to the docs.

**Comment by flaushi** [comment]
I'd appreciate the ULIDs a lot!

**Comment by pluk77** [comment]
@ramsey Going forward, would you recommend using UUID6 instead of InnoDB-optimised binary UUIDs for new projects? Is there an InnoDB performance difference between the two binary versions?

    /**
    * @ORM\Column(type="uuid_binary", unique=true)
    * @var Ramsey\Uuid\UuidInterface
    */
    protected $uuid;
    
    public function __construct()
    {
        $this->uuid = Uuid::uuid6();
    }

**Comment by ramsey** [comment]
At the binary level, the ordered-time version 1 UUIDs are nearly identical to version 6 UUIDs. The primary difference is the version bits. I do not believe there should be any InnoDB performance difference between them (I have not benchmarked this).

I hesitate to make a hard recommendation right now, since version 6 is still a long way from becoming a standard recommendation, but I do not foresee any changes in the byte structure that could result in BC breaks, so it *should* be safe to use.
