### ISSUE TITLE
Trait defines the same property in the composition {entity}

### ISSUE THREAD

**Issue by abelardolg** [ramsey/uuid-doctrine#83]
Hi.
After reading your post about Uuids:[UuiDs]( https://medium.com/@galopintitouan/auto-increment-is-the-devil-using-uuids-in-symfony-and-doctrine-71763721b9a9), I installed your package.

"My" EntityIdTrait is yours.
My (unique) entity starts with:

```
class Deuda
{
    use EntityIdTrait;

    /**
     * @var UuidInterface
     *
     * @ORM\Id
     * @ORM\Column(type="uuid", unique=true)
     * @ORM\GeneratedValue(strategy="CUSTOM")
     * @ORM\CustomIdGenerator(class="Ramsey\Uuid\Doctrine\UuidGenerator")
     */
    private $id;

    /**
     * The internal primary identity key.
     *
     * @var UuidInterface|null
     *
     * @ORM\Column(type="uuid", unique=true)
     */
    protected $uuid;

// The rest of the file contains boring getters and setters and more fields
```
I also updated the config/packages/doctrine.yaml file:
```
types:
         uuid:  Ramsey\Uuid\Doctrine\UuidType
```
After these changes, I got this message:
When I run my SF4 app, I got this message:
![image](https://user-images.githubusercontent.com/22522883/61581723-2769e580-ab22-11e9-90ea-b639ae08733d.png)

Symfony version: 4.x.x

What's wrong?

Kindest regards

**Comment by ramsey** [comment]
Hi! I didn't write that article, but I took a look at it, and the `EntityIdTrait` listed defines the `$id` property as `protected`. That's what this error means. In your `Deuda` class, if you change `$id` from `private` to `protected`, it should work.

Alternately, in the `EntityIdTrait`, if you change it from `protected` to `private`, it should also work.

Since the visibility differs, they're considered incompatible definitions, and since the PHP interpreter actually includes at compile time the trait's code as part of the class that includes the trait, it appears (to the interpreter) that you're defining `$id` twice. Since the trait defines both the `$id` and `$uuid` properties, there's no need to also define them in `Deuda`; they're technically already part of `Deuda`, as far as the interpreter is concerned.

Hope this helps!
